#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 3.6

services: postgresql

env:
  - DATABASE_URL=postgres://postgres@localhost/mendelmd


before_install:
  - export DJANGO_SETTINGS_MODULE=mendelmd.settings
  - export PYTHONPATH=$HOME/builds/raonyguimaraes/mendelmd
  - export PIP_USE_MIRRORS=true
  - export PIP_USE_MIRRORS=true


install:
  - pip install -r requirements.txt
  - pip install psycopg2-binary --quiet

before_script:
  - psql -c "CREATE DATABASE mendelmd;" -U postgres

script:
- python manage.py migrate --noinput

addons:
  postgresql: "9.6"