# To load elastic search as a docker container set vm.maxmap_count in local machine:
# sysctl -w vm.max_map_count=262144
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
version: '2'
volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:

services:
  db:
    image: postgres
    volumes:
      - ./data/postgresql_data:/var/lib/postgresql/data/
    restart: always
    networks:
      - esnet

  web:
    build: .
    command: bash docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - es01
    networks:
      - esnet

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    
 # annotator:
 #  build: ./compose/annotator